### ISSUE TITLE
Smart completion - Some glitches

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#6] opened 2016-12-25 10:02 UTC
There is more work to improve the logic to detect if we edit a option value vs add new option

**Comment by davsclaus** [comment] 2016-12-25 10:03
Also the camel-catalog has that problem if you have half complete option, then it may not be able to parse the parameters. Also if the string ends with '&' or '?' etc.

And also there is little work to improve if the string value has '?' or not, and when you add the first new option, then we should automatic add '?' or not etc.

**Comment by davsclaus** [comment] 2016-12-25 10:03
Basically just try the smart completion in Java for a while to find those small glitches.

**Comment by davsclaus** [comment] 2016-12-28 19:20
There is a few issues when positioning cursor in the middle of option or value and then pressing ctrl + space. We need to find out if its a option or value and react accordingly, so you can easily also edit an enum etc.

**Comment by fharms** [comment] 2016-12-29 07:21
I also think it's not common standard we insert "?" or "&" active for the user as we do here [CamelSmartCompletionEndpointOptions](https://github.com/davsclaus/camel-idea-plugin/blob/b5607faa6fe4561b151dcbda3b5b6d2108f3b3b1/src/org/apache/camel/idea/CamelSmartCompletionEndpointOptions.java#L54)

Take for example Java completion is does not prepare the lookup for a new value, the user has to active press "." or ctrl-space

**Comment by davsclaus** [comment] 2016-12-29 07:47
We do this to separate the values, then you can just press ctrl + space, select the option, enter the value and then press + space again.

When you do that it feels good that the plugin takes care of the ? or & for you.

**Comment by fharms** [comment] 2016-12-29 08:16
I just makes it more complex to handle half completion, you will have to parse the string for the closest "?" or "&" to make sure we don't insert a "?" / "&" in the middle of the string.

I think they are used to active the completion from java by adding the "." or "(" before they press CTRL + space, but we change that behavior by automatic inserting separator character. 

I leave it as it is, and we can see if need to change it later

**Comment by davsclaus** [comment] 2016-12-29 09:00
Yes the world is not easy. 

Its a feature that I want so I dont have to fight about & or &amp; just to add a new option.

**Comment by davsclaus** [comment] 2017-01-01 18:01
We could try to add smart completion for values also work if the cursor is in the middle of a value, eg
`jms:queue:foo?acknowledgeModeName=CLIENT_AC_here is the cursor_KNOWLEDGE&concurrentConsumers=5`

Currently you need to move the cursor right after the `=` sign. What we can do is to back search and find whether the first found is `=` or `?|&'. Then we know if its a value vs option.

**Comment by davsclaus** [comment] 2017-01-01 18:10
If you put the cursor in the middle of a option name, and then press ctrl + space, and then select a nice option name, then the old option is not completely removed, eg

`from("timer:trigger?delay={{myDelay}}")`

I have the cursor in the middle of the `delay` option, and then change that to another option
`from("timer:trigger?del&fixedRate=ay={{myDelay}}")`

**Comment by fharms** [comment] 2017-01-01 18:45
It possible to add a insert handler to the LookupElementBuilder where you
can control the cursor

Den 1. jan. 2017 7.10 PM skrev "Claus Ibsen" <notifications@github.com>:

**Comment by fharms** [comment] 2017-01-28 12:24
Improved the smart completion a little. It will now filter the completion list on the pre entered option.
There is still cases I need to handle, but it is working much better.

![improved-smart-completion](https://cloud.githubusercontent.com/assets/1123285/22396563/d3a94748-e55c-11e6-9922-90852f382456.gif)

**Comment by fharms** [comment] 2017-01-29 08:05
@davsclaus when I use smart completion on endpoint values it deletes the rest of the string if I place the cursor right after "=".

Is this intended behaviour, because it seem strange IMHO?

See screenshoot:
![improved-smart-completion-error](https://cloud.githubusercontent.com/assets/1123285/22402726/e0aaaf40-e601-11e6-9d24-159630fb9733.gif)

**Comment by davsclaus** [comment] 2017-01-29 12:24
AFAIR idea works differently when you use either TAB or ENTER in the code completion list. 

Try with regular java code completions on methods etc.

And yeah I also think there is maybe somewhere we cut the lookup uri from the cursor position, and therefore depending on either TAB or ENTER need to add that back somehow.

But also I dont think anyone want a ENTER or TAB to remove the other options even if IDEA may do that on java methods etc.

**Comment by fharms** [comment] 2017-01-29 21:18
@davsclaus the completion logic gonna change a bit with the new improved functionality and bug fixes. With version 0.3.5 we didn't have to add "?" or "&" to get the completion list for the endpoint URI when press ctrl + enter. This had a number of side effects when the cursor was in the middle of a optionor value it could not resolve it and insert / replace it correctly.

This will change so you will have to add "?" or "&" and ctrl + enter to activate the completion list, this is similar to the way the Java completion works 

The reason is the way smart completion work with pre search and in replacement of options / values it's too hard to determine what the intention of the user is at this point. Does they press ctrl-space to get a list of possible values or do they want a list of possible options

In the example below the option "exchangePattern" has an unresolved value, and if you place the cursor at the end of the line it should resolve the rest of the value list contains "Ro". 

>timer:trigger?repeatCount=0&exchangePattern=Ro\<cursor\>
<img width="550" alt="screen shot 2017-01-29 at 14 39 29" src="https://cloud.githubusercontent.com/assets/1123285/22404415/e1feaa66-e630-11e6-8642-75d84d55a559.png">

**Comment by fharms** [comment] 2017-02-01 18:34
Close this since #250 is merged. if anything shows up I'll prefer to have new ticket on the issue.

**Closed by fharms** 2017-02-01 18:34 UTC
