### ISSUE TITLE
Real time validation of string literals using string concat and field reference

### ISSUE THREAD

**Issue by davsclaus** [davsclaus/camel-idea-plugin#220] opened 2017-01-17 20:12 UTC
We should try to add support for validation when users break their strings into multiple lines

And further down the road add support for string concat with simple values such as numbers, booleans etc, or field references etc. 

We do a bit of digging for this in the Camel Maven Plugin
https://github.com/apache/camel/blob/master/tooling/camel-route-parser/src/main/java/org/apache/camel/parser/helper/CamelJavaParserHelper.java#L645

**Comment by davsclaus** [comment] 2017-01-17 20:12
See #206

**Comment by fharms** [comment] 2017-02-11 12:22
It's fairly easy to get the complete wrapped string within the PSI tree
> PsiTreeUtil.getParentOfType(element, PsiPolyadicExpression.class);

But it's whole different problem to make it work with smart completion.....

**Comment by fharms** [comment] 2017-02-12 08:09
First preview of smart completion with wrapped strings
![smart-completion-wrapped-strings](https://cloud.githubusercontent.com/assets/1123285/22860595/f177158c-f102-11e6-8423-b5838be42e81.gif)

**Comment by fharms** [comment] 2017-02-15 09:09
The validation for multiline XML file seems to work out of the box. For Java file I need to do a little work before this will work.

**Comment by fharms** [comment] 2017-02-18 15:20
Good progress with getting the Java endpoint multi line validation to work
<img width="534" alt="screen shot 2017-02-18 at 16 18 57" src="https://cloud.githubusercontent.com/assets/1123285/23094275/18421c14-f5f6-11e6-9369-e1379d8b8c3b.png">

**Comment by fharms** [comment] 2017-02-20 10:36
This work for XML and java, but we still need to make this work for other languages like scala, groovy etc.

The problem is we don't have the SDK support for other languages which make it a bit more difficult to determine if it's a polyadic expression

**Comment by fharms** [comment] 2017-03-03 06:54
Close this since we need to find a solution for #285 first. I will create separate issues for other languages

**Closed by fharms** 2017-03-03 06:54 UTC
